image: alpine:latest

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp index.html public/index.html
  artifacts:
    paths:
      - public
  only:
    - main
  environment:
    name: production
    url: https://$CI_PROJECT_NAMESPACE.gitlab.io/$CI_PROJECT_NAME
